### ISSUE TITLE
cqerl cannot be used on OTP23

### ISSUE THREAD

**Issue by bettio** [cqerl/cqerl#162] opened 2020-06-12 10:24 UTC
cqerl cannot be used on OTP23 since it depends on some old NIF packages that are not able to build anymore on OTP23.
Proposed solution: https://github.com/matehat/cqerl/pull/161

**Comment by matehat** [comment] 2020-06-12 12:19
Merged! I also created and new tag and published the new 1.1.3 on hex.pm. Can you tell me if it fixes the issue?

**Comment by bettio** [comment] 2020-06-12 13:08
snappy 1.1.1 (the one from hex) cannot work, it makes use of liberl_interface which is no longer shipped with OTP23, so it fails to build.
snappy hex.pm package it looks to be no longer maintained, @benoitc removed its repo from github so it is even hard to try to patch it. So I found that other snappy package that is newer and makes use of a recent port_compile (pc) package.

**Comment by matehat** [comment] 2020-06-12 17:18
Ahhh I see. The issue is that with that other package, we can’t publish
cqerl to hex.pm anymore. I’ll see if I can publish that other snappy
package you found.

Le ven. 12 juin 2020 à 09:09, Davide Bettio <notifications@github.com> a
écrit :

**Comment by matehat** [comment] 2020-06-12 23:44
@bettio So I just published 1.1.4 that seems to solved this (builds with OTP 23). I change snappy dependency for snappyer, and bumped lz4 and uuid.

Can you confirm it works on your end?

**Comment by bettio** [comment] 2020-06-15 15:41
Now 1.1.4 works fine, thanks :)
Just two more things:
1. You didn't push the tag for 2.0.0 here on github
2. It would be great if you update and tag cqex (and publish it on hex.pm) 
I think this issue can be closed.

**Comment by matehat** [comment] 2020-06-16 02:09
Just did all of that. Thanks for the suggestions!

**Closed by matehat** 2020-06-16 02:09 UTC
